# Generated by Django 4.1.1 on 2022-10-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='Status',
            field=models.CharField(choices=[('DR', 'driver'), ('PR', 'passenger')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
